name: CLI Tests Develop

on:
  push:
    branches:
      - develop
      - feature/command_line

jobs:
  cli_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.sunangel/geoelevations
          key: ${{ runner.os }}-cli-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-cli-tests-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: bash run_cli_tests.sh
