name: Core Tests Develop

on:
  push:
    branches:
      - develop
      - feature/ci

jobs:
  unit_tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.sunangel/geoelevations
          key: ${{ runner.os }}-core-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-core-tests-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: bash Scripts/run_core_tests.sh
