name: Core Unit Tests Develop

on:
  push:
    branches:
      - develop

jobs:
  unit_tests:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.geoelevations
          key: ${{ runner.os }}-core-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: bash run_core_tests.sh
