name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-release
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: bash build_release.sh
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: SunangelBinaries*
