name: Run Go Unit Tests

on:
  push:
    branches:
      - master
      - develop
      - feature/continuous_integration

jobs:
  unit_tests:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: bash run_tests.sh
